### ISSUE TITLE
[Create New Issue]: Issue in one of the workflows of the repo

### ISSUE THREAD

**Issue by Jassi10000** [NFT-Cryptonaut/NFT-Emporium#9]
### Description

Description :
 I want to tell that till the date I have forked the repo , one of your workflow is failing again and again on my forked version whenever I make any changes to the repo and make a PR , I have to delete the PRs again and again , I request you to please check and correct that 

### Domain

Open Source

### Type of Contribution

Others

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by bartick** [comment]
Is it `Automatic Approve` workflow.
I would like to fix that issue under GSSoC'22
Can I work on this issue ??

**Comment by Suvraneel** [comment]
@Jassi10000  Disable the workflow on your fork
It is not supposed to work there... Bcz its configured with a personal access token

**Comment by Suvraneel** [comment]
@bartick  I'm sorry but its working as intended. 
Thanks for asking though
